# -*- coding: utf-8 -*-
# ======================================
# @File    : 5345.py
# @Time    : 2020/3/1 13:17
# @Author  : Rivarrl
# ======================================
from algorithm_utils import *

class Solution:
    """
    [5345. 通过投票对团队排名](https://leetcode-cn.com/problems/rank-teams-by-votes/)
    """
    @timeit
    def rankTeams(self, votes: List[str]) -> str:
        n = len(votes[0])
        m = len(votes)
        s = {e:0 for e in votes[0]}
        k = 1
        for i in range(n-1, -1, -1):
            for v in votes:
                s[v[i]] += k
            k *= (m+1)
        ss = sorted([[v, -ord(k)] for k, v in s.items()], reverse=True)
        return ''.join([chr(-e[1]) for e in ss])


if __name__ == '__main__':
    a = Solution()
    a.rankTeams(["ABC","ACB","ABC","ACB","ACB"])
    a.rankTeams(["WXYZ","XYZW"])
    a.rankTeams(["ZMNAGUEDSJYLBOPHRQICWFXTVK"])
    a.rankTeams(["BCA","CAB","CBA","ABC","ACB","BAC"])
    a.rankTeams(["M","M","M","M"])
    a.rankTeams(["TNYGHIOKWJ","JONIGWHYTK","JIKWONHTYG","YGIJWTHNOK","OJTKIYNWGH","IYNJTHGOWK","GKOHIYJTNW","HKOJGWINYT","GTYKOHNIJW","YIGOKTJHWN","WGITOHNYJK","GWKTIHJONY","NHKYWTIJGO","IWKGYOHTJN","TKNYGJWIHO","GOWTHNYJKI","GINHJTOYKW","JKIHTGOWNY","JHIYTGKWON","TWJKIHYNOG","TNIHKWGOJY","JGWTOYKIHN","NGYTJOIKWH","YKJWOGNIHT","YTKOHNIJGW","HNOTWGKJIY","YIGOJHNWTK","GWOKITJYNH","HGTIJWONYK","JHOTIKGNWY","KIJWHTNOGY","GKTNWJHYIO","OGHJWYTIKN","WKHJYTNIOG","JNIWGTOKHY","ONHKWYITGJ","NTGOJKYHWI","JNYTGOIWKH","YGNTOJKWIH","OKYTNJWGHI","TJWNOYHKIG","JWOYKTNIGH","TNWKGJOHYI","HOWJINTGYK","YNIOWKTHJG","IOWTHGYJKN","THIKNYGOWJ","GKOJHWIYTN","IGOWJYNHTK","THOGJIYNKW","KGYWJNOTIH","ITOWNYHJGK","YJONGHTKWI","TYGNIKJOWH","IHNTGJYOKW","GTIKJWNHYO","YWJKNOGTIH","IJGHYTNWOK","IKWGTHNJYO","KGOITJHNWY","KWHGYTINOJ","HYJKWGNOTI","JTGINOWKYH","HKTGOWIJYN","JWONIKHTYG","KIJHNYGOWT","NOIGWYKTHJ","HJYGTOKWIN","YJNHWGIKTO","GIOWKNYJHT","HIWNGKJOTY","HTNWOJYKIG","HKTJNWYGIO","HWTGYOKNIJ","KONHYJTWIG","JGOKNYTWIH","WOJHKYITNG","NWOKJITYGH","HKINTYWJOG","GHJYNWOTKI","THGKNWIYJO","HONKJYITGW","JWTINYOKHG","HOIYGTJWNK","WGNHYIOJTK","YTGNIHKOWJ","KTIJYNOHGW","YJTHKOIGWN","NKOHYTIJWG","OINJGKWYTH","JHWGKTOIYN","NIGOWTJYKH","INWTJGYKOH","TNOGWHJKYI","WYNHOTJIGK","KOTHNIGJYW","OJTWHNIGKY","NKTJYIGHOW","YOJKTIHNGW","YGJKTHOWIN","GWTNYKIOHJ","NHJIWOTGYK","GNYTHWIKOJ","YJNIWTKGHO","JOIKWTHGYN","IWKGJOTNYH","IWNOHYTJGK","KWONJGYIHT","NTIGHYOJKW","GIKHNOWJTY","GJTNIHYWKO","WGYKJHOITN","JTYKHOWNGI","YJGTWIKONH","OHGJYKNTIW","NYGWOTHIKJ","GWYKTHIONJ","YTHJOKWNGI","WYHIJGTNKO","KYGTWJNHIO","HKNYJIGWTO","OYJGKNIWHT","KYHNJGTWIO","NWYKJOHGIT","HGJOWYNTIK","NOYWKJHITG","NGHOKWITJY","OJIYHGWKNT","OIGHJTWKYN","HIJWONKGYT","WTHYIOKJGN","HTWOJKYIGN","TYNWHJOIGK","HKJTYNIGWO","GOJTIYHKNW","OTKGHYNWJI","JNWHOTYGIK","GHJKYONTIW","NHJTYIOWKG","NTJGWOKIYH","KNTIOGWJYH","WHJTIGKONY","NJWGTHKYOI","WNYJIHTOGK","ONKTHGIWJY","YIKWNGTJOH","GYHKOJWTNI","YKHNOJWTGI","GOKNIYJHWT","HOKGWTYNIJ","KOJTGNWIHY","INYTHGKOWJ","ONTYJGHKIW","IHTWGYKJON","WYKHNOJITG","OJHTGIKNWY","NYIOTHJKGW","TKWGNJOYHI","YIWGNOJKTH","TWGKYJONHI","WYHTGNOJKI","OYJIHNWGTK","NGOTWKIYHJ","IWNKTGOHJY","INTHYOWKJG","YWOKGIHJTN","NITGWJYOKH","GOIKHJNTWY","YIGJTKONHW","WYHKOIJTGN","OYGKINTWJH","GYKJNTHIWO","HGWINYTOKJ","TKIWHYJNGO","WJYOIGHNKT","YJHTKGWNIO","KIGTNYWJHO","OWNJIHTGYK","YNKHJTGWIO","YHWITGKONJ","IOKJHGTYWN","OJYIHWTKGN","GWYKJNIOHT","NWHYGKTIOJ","TOHKWIYNJG","HOTJGNIKWY","WYHOKGJNIT","HTYNKJWGIO","KHIYJGOTWN","WNOGHITJYK","WOJNKHIGYT","NJHOTIYKWG","IJGWONYTHK","GHNKWYOTJI","TNOKJHIYWG","HJYNGWIKTO","KWHJYGTOIN","OHGKTJWYIN","WNKYIJTHOG","JOTHWNGKYI","JIWNYOGHKT","IJWGKTHNOY","OYNHWJGTIK","WJNOYKGTIH","JGWNHITYKO","WTJHOIKGNY","ONTKJWGHYI","GKOWTHJIYN","GHWTNJOYIK","NJTIKOGYHW","YJGKOTIWHN","TWYJNGKOHI","GIWNOTKJYH","HOIWNJKGYT","TNIGJYHWOK","WHGIOYTKJN","TWKHNIJYGO","GKTJHIWONY","KNIGJHWYOT","IJWGOTNHKY","WYNJTGKIOH","HGYWITJNKO","HJGTOYNWIK","IOWTJNYHKG","GJWTINYOKH","WGHJNOITYK","TOKJHGWINY","WYHGTINKOJ","OKNTJWHYGI","KOGITNWHJY","HWYINKTOGJ","HYIGWTKNJO","OTIHKNJYGW","NWGHYTJKOI","OIJWTHNGYK","IWNOYKTJHG","KOTWJINGHY","JTWGIKYONH","HJYNKWGTOI","IHTYWOKGJN","HGKTIOWNYJ","WNOHJGTKYI","GNYWJKIOTH","KTGYJIONWH","GOWYHIJNKT","YWHOJGNIKT","NGKOWJHITY","OYGWKJNTHI","NIYHGOKWJT","IOGYKWNJHT","JGYIWHONTK","JHGTNWIYKO","WHJNGTYKOI","KYNWJTOGHI","YJTHOKGIWN","IYWHGONTJK","KNIYJHWGOT","WGKONJTHYI","IJWGKTHOYN","WGOJKINYTH","KJYOIGHNWT","ITJYWHOKGN","TJHIKOGWYN","GIYTJOWNHK","YWIGNOHTKJ","KWYNIJOGHT","NHYWOTKJIG","GYNOTKJWHI","HGKWNYIJTO","WHGOKNJTIY","KYIHWGOJNT","WOGIJYKHTN","JIHWKYGNTO","JWHYNKTIGO","WNHYOIKGJT","YHWKIGOJNT","WHOJINYGTK","WNOIYTKHGJ","IWJNGYTHKO","HTKNJWYIGO","IWOGJTKHYN","OGNTWJHKYI","JIGYTNKWOH","KGYNOIHJTW","TNWOJIHGYK","IKYWNHJGTO","JNGHITYOKW","TWIYNGJHKO","IOGWJKYNHT","WIOKJTNGHY","IYKJWGONTH","OYIWGHNTJK","IGKTHWJONY","TNHIKWJYOG","JKTHOIYWNG","JHKTIGWOYN","TWJNGKIHYO","GOYJTIWHNK","TOHIKYJGWN","WIYGKJHTON","JHITWOYNGK","GWKJOYITHN","ONWGYJIHTK","TKJOWYHING","WTNGKJHIYO","HJONWKGYTI","KOGWIJTHNY","KYIJGONWTH","WNOTKGHYIJ","YOGHNJWITK","HKWITYNOJG","YKJNITHWGO","KNOWHITYJG","KIWHJNYOGT","YWHTGJKION","JHIKGYTOWN","GOYNJTIWHK","IGNJHOTWYK","WTIHJOKNGY","OTIYJHWNKG","TIJNOKGHWY","IYNOGWHTJK","TIYHWKONGJ","JKWNYTOGHI","NOJGWIHTYK","KINJOWGHTY","IJKNHOGYTW","TOGIHNYJWK","NOWIKYHGTJ","HWJIOGNTKY","NGHKWTYJIO","NKIOJWYHTG","WIHNGJTOYK","OYINKGJTWH","OJWNIKTHGY","GJOHYNWTKI","NKJOITHYWG","JWYTKNOIHG","KIJONTYWHG","NOWKJGHITY","HNWKJYTIGO","OJTWHYGKIN","NOTWHIYKJG","KTINGYOWJH","WGJYTNHIKO","TKNOJWYIGH","OJTWGHNIYK","JWTGYNOHKI","KGHINYWJTO","NTJIGKYHWO","GIHOTWJNYK","TYINGOWKHJ","TONIYGJKWH","ONTWHKJYGI","KJTWGYNOIH","TOWIHNGJYK","YIGHTNOJKW","GHTJOYINWK","YJTOHGINWK","JHGTYKNOWI","THIWKOJYNG","WIHYTONJKG","KWGYHNTIJO","WNTOKGJHYI","WYGIJTKNOH","INYWHJTGOK","WHYJIGNOKT","NYTWGKOHJI","TNGIWYKHOJ","YJGKWHIONT","IJKOTGNWHY","WNHTJYIKOG","YTOJIKGHWN"])